# -*- coding: utf-8 -*-
#
# QGIS Tutorials documentation build configuration file, created by
# sphinx-quickstart on Wed Aug 14 20:19:30 2013.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys, os
import sphinx_bootstrap_theme

# sys.path.insert(0, os.path.abspath('.'))

sys.path.append(os.path.abspath("./_ext"))

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'gisphinx'
]

templates_path = ['_templates']

source_suffix = '.rst'

master_doc = 'index'

project = 'giSphinx'
copyright = '2019, Bu Kun'


version = 'v1.0'
release = '1'

exclude_patterns = []

pygments_style = 'sphinx'

gettext_compact = True

html_theme = 'bootstrap'

html_theme_options = {
    'bootswatch_theme': 'united',
    'navbar_pagenav': False,
    'navbar_site_name': 'Tutorials List'
}

html_theme_path = sphinx_bootstrap_theme.get_html_theme_path()

html_title = 'Publising Maps'
language = 'zh'

html_last_updated_fmt = '%b %d, %Y'

html_sidebars = {
    '**': ['custom_sidebar.html'],
}

html_use_index = False
html_show_sourcelink = False
author = 'bukun'
